# This is a sample plugin.yml
# For more infomration refer to http://wiki.bukkit.org/Plugin_YAML
main: edu.unca.twreese.shuffle.shuffle
name: ${project.name}
version: ${project.version}
author: SampleAuthor
description: ${project.description}
commands:
  shuffle:
    description: set the sample message
    usage: /<command>
    permission: shuffle.shuf
permissions:
  shuffle.*:
    description: gives all permissions of the shufflePlugin
    default: true
    children:
      shuffle.shuf:
        description: Randomly Teleports you within 500 blocks
      shuffle.rain:
        description: Make it rain!
      shuffle.oprahpig:
        description: Gives the player you type in after a pig